/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminPanelRouteImport } from './routes/admin._panel'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin.forgot-password'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as AdminSetupRouteImport } from './routes/admin.setup'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as AdminPanelDashboardRouteImport } from './routes/admin._panel.dashboard'
import { Route as AdminPanelEnquiriesRouteImport } from './routes/admin._panel.enquiries'
import { Route as AdminPanelProfileRouteImport } from './routes/admin._panel.profile'
import { Route as AdminPanelSettingsRouteImport } from './routes/admin._panel.settings'
import { Route as AdminPanelDestinationsIndexRouteImport } from './routes/admin._panel.destinations.index'
import { Route as AdminPanelDestinationsNewRouteImport } from './routes/admin._panel.destinations.new'
import { Route as AdminPanelDestinationsIdEditRouteImport } from './routes/admin._panel.destinations.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelRoute = AdminPanelRouteImport.update({
  id: '/admin/_panel',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin/forgot-password',
  path: '/admin/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin/reset-password',
  path: '/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin/setup',
  path: '/admin/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelDashboardRoute = AdminPanelDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelEnquiriesRoute = AdminPanelEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelProfileRoute = AdminPanelProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelSettingsRoute = AdminPanelSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelDestinationsIndexRoute =
  AdminPanelDestinationsIndexRouteImport.update({
    id: '/destinations/',
    path: '/destinations/',
    getParentRoute: () => AdminPanelRoute,
  } as any)
const AdminPanelDestinationsNewRoute =
  AdminPanelDestinationsNewRouteImport.update({
    id: '/destinations/new',
    path: '/destinations/new',
    getParentRoute: () => AdminPanelRoute,
  } as any)
const AdminPanelDestinationsIdEditRoute =
  AdminPanelDestinationsIdEditRouteImport.update({
    id: '/destinations/$id/edit',
    path: '/destinations/$id/edit',
    getParentRoute: () => AdminPanelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/admin': typeof AdminPanelRouteWithChildren
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/setup': typeof AdminSetupRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/admin/dashboard': typeof AdminPanelDashboardRoute
  '/admin/enquiries': typeof AdminPanelEnquiriesRoute
  '/admin/profile': typeof AdminPanelProfileRoute
  '/admin/settings': typeof AdminPanelSettingsRoute
  '/admin/destinations/new': typeof AdminPanelDestinationsNewRoute
  '/admin/destinations/': typeof AdminPanelDestinationsIndexRoute
  '/admin/destinations/$id/edit': typeof AdminPanelDestinationsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/admin': typeof AdminIndexRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/setup': typeof AdminSetupRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/destinations': typeof DestinationsIndexRoute
  '/admin/dashboard': typeof AdminPanelDashboardRoute
  '/admin/enquiries': typeof AdminPanelEnquiriesRoute
  '/admin/profile': typeof AdminPanelProfileRoute
  '/admin/settings': typeof AdminPanelSettingsRoute
  '/admin/destinations/new': typeof AdminPanelDestinationsNewRoute
  '/admin/destinations': typeof AdminPanelDestinationsIndexRoute
  '/admin/destinations/$id/edit': typeof AdminPanelDestinationsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/admin/_panel': typeof AdminPanelRouteWithChildren
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/setup': typeof AdminSetupRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/admin/_panel/dashboard': typeof AdminPanelDashboardRoute
  '/admin/_panel/enquiries': typeof AdminPanelEnquiriesRoute
  '/admin/_panel/profile': typeof AdminPanelProfileRoute
  '/admin/_panel/settings': typeof AdminPanelSettingsRoute
  '/admin/_panel/destinations/new': typeof AdminPanelDestinationsNewRoute
  '/admin/_panel/destinations/': typeof AdminPanelDestinationsIndexRoute
  '/admin/_panel/destinations/$id/edit': typeof AdminPanelDestinationsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/admin'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/reset-password'
    | '/admin/setup'
    | '/destinations/$slug'
    | '/admin/'
    | '/destinations/'
    | '/admin/dashboard'
    | '/admin/enquiries'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/destinations/new'
    | '/admin/destinations/'
    | '/admin/destinations/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/admin'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/reset-password'
    | '/admin/setup'
    | '/destinations/$slug'
    | '/destinations'
    | '/admin/dashboard'
    | '/admin/enquiries'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/destinations/new'
    | '/admin/destinations'
    | '/admin/destinations/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/admin/_panel'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/reset-password'
    | '/admin/setup'
    | '/destinations/$slug'
    | '/admin/'
    | '/destinations/'
    | '/admin/_panel/dashboard'
    | '/admin/_panel/enquiries'
    | '/admin/_panel/profile'
    | '/admin/_panel/settings'
    | '/admin/_panel/destinations/new'
    | '/admin/_panel/destinations/'
    | '/admin/_panel/destinations/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  AdminPanelRoute: typeof AdminPanelRouteWithChildren
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSetupRoute: typeof AdminSetupRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_panel': {
      id: '/admin/_panel'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/admin/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_panel/dashboard': {
      id: '/admin/_panel/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminPanelDashboardRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/enquiries': {
      id: '/admin/_panel/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminPanelEnquiriesRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/profile': {
      id: '/admin/_panel/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminPanelProfileRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/settings': {
      id: '/admin/_panel/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminPanelSettingsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/destinations/': {
      id: '/admin/_panel/destinations/'
      path: '/destinations'
      fullPath: '/admin/destinations/'
      preLoaderRoute: typeof AdminPanelDestinationsIndexRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/destinations/new': {
      id: '/admin/_panel/destinations/new'
      path: '/destinations/new'
      fullPath: '/admin/destinations/new'
      preLoaderRoute: typeof AdminPanelDestinationsNewRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/destinations/$id/edit': {
      id: '/admin/_panel/destinations/$id/edit'
      path: '/destinations/$id/edit'
      fullPath: '/admin/destinations/$id/edit'
      preLoaderRoute: typeof AdminPanelDestinationsIdEditRouteImport
      parentRoute: typeof AdminPanelRoute
    }
  }
}

interface AdminPanelRouteChildren {
  AdminPanelDashboardRoute: typeof AdminPanelDashboardRoute
  AdminPanelEnquiriesRoute: typeof AdminPanelEnquiriesRoute
  AdminPanelProfileRoute: typeof AdminPanelProfileRoute
  AdminPanelSettingsRoute: typeof AdminPanelSettingsRoute
  AdminPanelDestinationsNewRoute: typeof AdminPanelDestinationsNewRoute
  AdminPanelDestinationsIndexRoute: typeof AdminPanelDestinationsIndexRoute
  AdminPanelDestinationsIdEditRoute: typeof AdminPanelDestinationsIdEditRoute
}

const AdminPanelRouteChildren: AdminPanelRouteChildren = {
  AdminPanelDashboardRoute: AdminPanelDashboardRoute,
  AdminPanelEnquiriesRoute: AdminPanelEnquiriesRoute,
  AdminPanelProfileRoute: AdminPanelProfileRoute,
  AdminPanelSettingsRoute: AdminPanelSettingsRoute,
  AdminPanelDestinationsNewRoute: AdminPanelDestinationsNewRoute,
  AdminPanelDestinationsIndexRoute: AdminPanelDestinationsIndexRoute,
  AdminPanelDestinationsIdEditRoute: AdminPanelDestinationsIdEditRoute,
}

const AdminPanelRouteWithChildren = AdminPanelRoute._addFileChildren(
  AdminPanelRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  AdminPanelRoute: AdminPanelRouteWithChildren,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSetupRoute: AdminSetupRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
